networks:
  my-laravel-network:
    driver: bridge

services:
  #    db:
  #        container_name: db
  #        image: mysql:8.0
  #        environment:
  #            MYSQL_ROOT_PASSWORD: yourpassword
  #            MYSQL_DATABASE: laravel_db
  #        ports:
  #            - "3306:3306"
  #        networks:
  #            - my-laravel-network

  app:
    image: novakvova/pv113_laravel:latest
#    build:
#        context: .
#        dockerfile: Dockerfile
    volumes:
        -   /data/website/images:/var/www/html/public/upload
#        -   D:\images:/var/www/html/public/upload
    #    depends_on:
    #      - db
    ports:
      - "8000:8000"
    #        volumes:
    #            - uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - my-laravel-network
  client:
    image: novakvova/pv113-client:latest 
    ports:
      - "5050:80" 
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
